#!/usr/bin/env python3
"""Bake the dialogue font into src/glyphs.js as bit rows: 8x16 ASCII, 16x16 CJK.

    python tools/make_font.py [preview.png]

Uses SimSun (Windows) at 16 px: the font carries hand-drawn 16 px bitmap
strikes, so FreeType returns exact 1-bit glyphs (checked: 2 grey levels) and
the player never depends on system fonts at runtime.
"""
from PIL import Image, ImageDraw, ImageFont
import glob, json, re, sys

FONT = 'C:/Windows/Fonts/simsun.ttc'
ASCII = ''.join(chr(c) for c in range(32, 127))
# every non-ASCII character used anywhere in src/ (dialogue, buttons, prompts)
CJK = '战斗行动物品仁慈收视率' + '？！。，：…「」—～'
for f in glob.glob('src/*.js'):
    if f.replace('\\', '/').endswith(('glyphs.js', 'assets.js', 'analysis.js')):
        continue
    CJK += ''.join(re.findall(r'[^\x00-\x7f]', open(f, encoding='utf-8').read()))
CJK = ''.join(ch for ch in dict.fromkeys(CJK) if ch.isprintable() and ch not in '♥★←→↑↓◀▶●')

font = ImageFont.truetype(FONT, 16)


def bake(ch, w):
    img = Image.new('1', (w, 16), 0)
    d = ImageDraw.Draw(img)
    d.fontmode = '1'
    d.text((0, 0), ch, font=font, fill=1)
    rows = []
    for y in range(16):
        v = 0
        for x in range(w):
            if img.getpixel((x, y)):
                v |= 1 << (w - 1 - x)
        rows.append(v)
    return rows


glyphs = {}
for ch in ASCII:
    glyphs[ch] = [8, bake(ch, 8)]
for ch in CJK:
    glyphs[ch] = [16, bake(ch, 16)]

# Command buttons: the Chinese build letters them in a heavy blocky face (~28x28 game px,
# strokes ~4 px; see tools/recover_buttons.py and work/btn_cmp2.png against the recording).
# Microsoft YaHei Bold rendered large, area-averaged onto a 14x14 grid and thresholded at
# 0.42 matches its weight and shapes; drawn at 2x.
import numpy as np
BTN_FONT, BTN_N, BTN_TH = 'C:/Windows/Fonts/msyhbd.ttc', 14, 0.42


def bake_btn(ch, n=BTN_N, th=BTN_TH):
    big = n * 24
    f = ImageFont.truetype(BTN_FONT, int(big * 0.98))
    im = Image.new('L', (big, big), 0)
    d = ImageDraw.Draw(im)
    bb = d.textbbox((0, 0), ch, font=f)
    d.text(((big - (bb[2] - bb[0])) / 2 - bb[0], (big - (bb[3] - bb[1])) / 2 - bb[1]), ch, font=f, fill=255)
    a = np.asarray(im, dtype=np.float32).reshape(n, 24, n, 24).mean(axis=(1, 3)) / 255 > th
    return [int(sum(1 << (n - 1 - i) for i in range(n) if a[j, i])) for j in range(n)]


btn = {ch: [BTN_N, bake_btn(ch)] for ch in '战斗行动物品仁慈'}

with open('src/glyphs.js', 'w', encoding='utf-8') as f:
    f.write('// Generated by tools/make_font.py (SimSun 16 px bitmaps; buttons: YaHei Bold on a 14x14 grid) - do not edit by hand.\n')
    f.write('window.MV_GLYPHS = ')
    json.dump(glyphs, f, ensure_ascii=False, separators=(',', ':'))
    f.write(';\nwindow.MV_BTN_GLYPHS = ')
    json.dump(btn, f, ensure_ascii=False, separators=(',', ':'))
    f.write(';\n')

if len(sys.argv) > 1:
    chars = '战斗行动物品仁慈 收视率 12000 你按了我的开关。 BOMEI LV 1 HP 20/20'
    img = Image.new('L', (16 * len(chars), 16), 0)
    x = 0
    for ch in chars:
        w, rows = glyphs.get(ch, [8, [0] * 16])
        for yy, r in enumerate(rows):
            for xx in range(w):
                if r >> (w - 1 - xx) & 1:
                    img.putpixel((x + xx, yy), 255)
        x += w
    img.crop((0, 0, x, 16)).resize((x * 4, 64), Image.NEAREST).save(sys.argv[1])
print(len(glyphs), 'glyphs')
